#!/bin/bash

echo "¡Hola! Soy iceYami, bienvenido a mi perfil."

echo "¿Quieres jugar a un juego? (s/n)"
read respuesta

if [ "$respuesta" == "s" ]; then
    echo "¡Genial! Vamos a jugar a la ruleta rusa con una pistola Beretta."
    echo "¡Click! ¡Click! ¡Click! (suena el tambor de la pistola)"

    # Simular si hay una bala o no (50/50 de probabilidad)
    bala=$(($RANDOM % 2))
    
    if [ $bala -eq 1 ]; then
        echo "¡Oh no! ¡Había una bala en el cargador!"
        
        # Generar un porcentaje de acierto aleatorio
        acierto=$(($RANDOM % 101))
        
        if [ $acierto -eq 0 ]; then
            echo "¡Fallaste! ¡La bala fue disparada!"
        else
            echo "¡Uf! Sobreviviste esta vez."
        fi
    else
        echo "¡Uff! Parece que no había bala en el cargador. ¡Has tenido suerte!"
    fi
else
    echo "Oh, está bien. ¡Quizás la próxima vez!"
fi
